baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data-Driven Cyber-Physical Systems Lab'
theme = 'xmin'

[menu]
[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Papers"
url = "papers/"
weight = 2
